import "./globals.css";
import Navbar from "@/components/Navbar";
import Menu from "@/components/Menu";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Calabar House Fellowship",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar></Navbar>
        <Menu></Menu>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
